# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f572e9dbbc98a094f59f04bc6d24915b9bdd6dd4dcd2e0ea3a0366e89f847448bc72b7d9198f8c7294b9b260854dc7145dd76854035525e5a371b2e18b7cecb9

test:
  secret_key_base: 70db92613a103091fc9c935af9e8989581074b894d8c4b99397e514871e1b7c49c711dfe2a75254f93bd7957dd0f045ece7ecb8e624ce6643346112a6ae8ed9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
